
INSERT ALL
  INTO GENRE VALUES (1, '코미디')
  INTO GENRE VALUES (2, '로맨스')
  INTO GENRE VALUES (3, '공포')
  INTO GENRE VALUES (4, 'SF')
  INTO GENRE VALUES (5, '액션')
  INTO GENRE VALUES (6, '범죄')
  INTO GENRE VALUES (7, '다큐')
  INTO GENRE VALUES (8, '가족')
  INTO GENRE VALUES (9, '스포츠')
  INTO GENRE VALUES (10, '애니메이션')
 SELECT *
  FROM DUAL;
  